# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_veiculo_cadeirante'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='Zona',
            field=models.CharField(default='teste', max_length=200),
            preserve_default=False,
        ),
    ]
