# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_linha_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoParada', models.CharField(max_length=10)),
                ('Denomicao', models.CharField(max_length=250)),
                ('Endereco', models.CharField(max_length=250)),
                ('Lat', models.CharField(max_length=30)),
                ('Long', models.CharField(max_length=30)),
            ],
        ),
    ]
