# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_paradas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradas',
            name='Endereco',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
