# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_auto_20170309_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradas',
            name='Lat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paradas',
            name='Long',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
